### ISSUE TITLE
live editor crash

### ISSUE THREAD

**Issue by miguelvigo** [xAranaktu/FIFA-21-Live-Editor#10]
the live editor crash when i try to import a miniface  inn a editplayers tab.
can someone help me resolve this problem?

**Comment by xAranaktu** [comment]
Crash or freeze? You should read the [Importing Miniface](https://github.com/xAranaktu/FIFA-21-Live-Editor/wiki/Importing-Miniface) Guide.
Anyway,
- If you get DirectX error then it's because of wrong file format or size.
- If game freeze then you are not opening the game in windowed mode
- If the game just closes without any error/warning then idk. maybe live editor don't have permission to read the files or create new files.
